// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/contact" | "/projects" | "/blog" | "/blog/:slug" | "/*";
  };
  "./routes/layouts/home.tsx": {
    id: "routes/layouts/home";
    page: "/";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "./routes/layouts/main.tsx": {
    id: "routes/layouts/main";
    page: "/about" | "/contact" | "/projects" | "/blog" | "/blog/:slug" | "/*";
  };
  "./routes/about/index.tsx": {
    id: "routes/about/index";
    page: "/about";
  };
  "./routes/contact/index.tsx": {
    id: "routes/contact/index";
    page: "/contact";
  };
  "./routes/projects/index.tsx": {
    id: "routes/projects/index";
    page: "/projects";
  };
  "routes/blog/index.tsx": {
    id: "routes/blog/index";
    page: "/blog";
  };
  "routes/blog/details.tsx": {
    id: "routes/blog/details";
    page: "/blog/:slug";
  };
  "routes/errors/not-found.tsx": {
    id: "routes/errors/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layouts/home": typeof import("./app/./routes/layouts/home.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "routes/layouts/main": typeof import("./app/./routes/layouts/main.tsx");
  "routes/about/index": typeof import("./app/./routes/about/index.tsx");
  "routes/contact/index": typeof import("./app/./routes/contact/index.tsx");
  "routes/projects/index": typeof import("./app/./routes/projects/index.tsx");
  "routes/blog/index": typeof import("./app/routes/blog/index.tsx");
  "routes/blog/details": typeof import("./app/routes/blog/details.tsx");
  "routes/errors/not-found": typeof import("./app/routes/errors/not-found.tsx");
};